version: '2'

services:
  nginx:
    image: nginx:stable-alpine
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"

  tarantool1:
    image: 'progaudi/tarantool:1.10'
    command: tarantool /opt/tarantool/app.lua
    volumes:
      - ./app.lua:/opt/tarantool/app.lua
    environment:
      TARANTOOL_REPLICATION_SOURCE: "tarantool1,tarantool2,tarantool3"

  tarantool2:
    image: 'progaudi/tarantool:1.10'
    command: tarantool /opt/tarantool/app.lua
    volumes:
      - ./app.lua:/opt/tarantool/app.lua
    environment:
      TARANTOOL_REPLICATION_SOURCE: "tarantool1,tarantool2,tarantool3"

  tarantool3:
    image: 'progaudi/tarantool:1.10'
    command: tarantool /opt/tarantool/app.lua
    volumes:
      - ./app.lua:/opt/tarantool/app.lua
    environment:
      TARANTOOL_REPLICATION_SOURCE: "tarantool1,tarantool2,tarantool3"
